name: nbconvert
description: Convert Jupyter notebooks to Markdown (or other formats supported by nbconvert)
inputs:
  args:
    description: 'Arguments to pass to convert.py'
    required: true
    default: '--help'
  token:
    description: "GitHub Personal Access Token with 'repo' permissions (for pushing updated .md files back onto PR branch)"
    default: ${{github.token}}

runs:
  using: docker
  image: docker://runsascoded/nbconvert-action
  args:
    - -t
    - ${{inputs.token}}