name: Refresh .md's
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Build Docker
      run: |
        docker build -t runsascoded/nbconvert-action .
    - name: Convert README
      uses: ./
      with:
        args: -f -x
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Push Docker
      run: |
        docker tag runsascoded/nbconvert-action runsascoded/nbconvert-action:${{ steps.extract_branch.outputs.branch }}
        docker login -u runsascoded -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push runsascoded/nbconvert-action:${{ steps.extract_branch.outputs.branch }}
